### ISSUE TITLE
Create profile organisation

### ISSUE THREAD

**Issue by bathienle** [Cytomine-ULiege/.github#4]
# Description

Create a profile describing the organisation in general.

# Task

- [x] Add the Cytomine ULiège Logo
- [x] Add a summary of the organization
- [x] Add links to the organization page, documentation page, and the Cytomine project page
- [x] Add links to social media
- [x] Add link to discussion
